$('#repetido').hide();$('#bien').hide();$('#voto1').click(function(e){votar($(this).data('encuesta'),$(this).data('opcion'))});$('#voto2').click(function(e){votar($(this).data('encuesta'),$(this).data('opcion'))});$('#voto3').click(function(e){votar($(this).data('encuesta'),$(this).data('opcion'))});$('#voto4').click(function(e){votar($(this).data('encuesta'),$(this).data('opcion'))});$('#voto5').click(function(e){votar($(this).data('encuesta'),$(this).data('opcion'))});$('#voto6').click(function(e){votar($(this).data('encuesta'),$(this).data('opcion'))});$('#voto7').click(function(e){votar($(this).data('encuesta'),$(this).data('opcion'))});$('#voto8').click(function(e){votar($(this).data('encuesta'),$(this).data('opcion'))});$('#voto9').click(function(e){votar($(this).data('encuesta'),$(this).data('opcion'))});$('#voto10').click(function(e){votar($(this).data('encuesta'),$(this).data('opcion'))});$('#voto11').click(function(e){votar($(this).data('encuesta'),$(this).data('opcion'))});$('#voto12').click(function(e){votar($(this).data('encuesta'),$(this).data('opcion'))});$('#voto13').click(function(e){votar($(this).data('encuesta'),$(this).data('opcion'))});$('#voto14').click(function(e){votar($(this).data('encuesta'),$(this).data('opcion'))});$('#voto15').click(function(e){votar($(this).data('encuesta'),$(this).data('opcion'))});$('#voto16').click(function(e){votar($(this).data('encuesta'),$(this).data('opcion'))});$('#voto17').click(function(e){votar($(this).data('encuesta'),$(this).data('opcion'))});$('#voto18').click(function(e){votar($(this).data('encuesta'),$(this).data('opcion'))});$('#voto19').click(function(e){votar($(this).data('encuesta'),$(this).data('opcion'))});$('#voto20').click(function(e){votar($(this).data('encuesta'),$(this).data('opcion'))});$('#voto21').click(function(e){votar($(this).data('encuesta'),$(this).data('opcion'))});$('#voto22').click(function(e){votar($(this).data('encuesta'),$(this).data('opcion'))});$('#voto23').click(function(e){votar($(this).data('encuesta'),$(this).data('opcion'))});$('#voto24').click(function(e){votar($(this).data('encuesta'),$(this).data('opcion'))});function votar(id,ide){var _this=$(this);var cookies=document.cookie;var if_cookie=!1;var lista_cookies=cookies.split(';');for(i in lista_cookies){var buscar=lista_cookies[i].search('gr'+ide);if(buscar>-1){if_cookie=!0;break}};if(!if_cookie){$.post('/votar/'+ide).always(function(def){_this.removeClass('disabled')}).done(function(resp){if(resp.status=='ok')
{var date=new Date();date.setTime(date.getTime()+(90*24*60*60*1000));document.cookie="name"+ide+"=gr"+ide+"; expires="+date.toGMTString();alert('Voto realizado correctamente.')}else if(resp.status=='re')
{alert('Usted ya voto, no puede votar mas de una vez.')}
else{alert('Algo inesperado ocurrió en el servidor.','info')}}).fail(function(def){alert('Algo no salio bien, Sentimos mucho las molestias que esto pueda causar.')})}
else{alert('Usted ya voto, no puede votar mas de una vez.')}}
$('#btn_voto').click(function(e){e.preventDefault();var _this=$(this);if(_this.hasClass('disabled'))
return!1;var id=$('#imagen').data('encuesta');_this.addClass('disabled');var cookies=document.cookie;var if_cookie=!1;var lista_cookies=cookies.split(';');for(i in lista_cookies){var buscar=lista_cookies[i].search('gr'+id);if(buscar>-1){if_cookie=!0;break}};if(!if_cookie){$('.ldr').show();var data={ide:$('#ra_opcion:checked').val()};$.post('/votar/'+data.ide,data).always(function(def){$('.ldr').fadeOut();_this.removeClass('disabled')}).done(function(resp){if(resp.status=='ok')
{var date=new Date();date.setTime(date.getTime()+(90*24*60*60*1000));document.cookie="name"+"=gr"+id+"; expires="+date.toGMTString();$('#bien').fadeIn();$('.op').fadeOut()}else if(resp.status=='re')
{$('#repetido').fadeIn();$('.op').fadeOut()}
else{alert('Algo inesperado ocurrió en el servidor.','info')}}).fail(function(def){alert('Algo no salio bien, Sentimos mucho las molestias que esto pueda causar.')})}
else{$('#repetido').fadeIn();$('.op').fadeOut()}});$('#btnresul').click(function(e){e.preventDefault();$('.op').fadeOut();$(this).fadeOut();$('#repetido').fadeOut();$('#bien').fadeOut();$('.resul').show();$('#btnatras').fadeIn()});$('#btnatras').click(function(e){e.preventDefault();$('.op').fadeIn();$(this).fadeOut();$('#btnresul').fadeIn();$('#repetido').fadeOut();$('#bien').fadeOut();$('.resul').hide();$('#btnatras').fadeOut()});$('#btn_voto2').click(function(e){e.preventDefault();var _this=$(this);if(_this.hasClass('disabled'))
return!1;var id=$('#imagen').data('encuesta');_this.addClass('disabled');var cookies=document.cookie;var if_cookie=!1;var lista_cookies=cookies.split(';');for(i in lista_cookies){var buscar=lista_cookies[i].search('gr'+id);if(buscar>-1){if_cookie=!0;break}};if(!if_cookie){$('.ldr').show();var data={ide:$('#ra_opcion:checked').val()};$.post('/votar/'+data.ide,data).always(function(def){$('.ldr').fadeOut();_this.removeClass('disabled')}).done(function(resp){if(resp.status=='ok')
{var date=new Date();date.setTime(date.getTime()+(90*24*60*60*1000));document.cookie="name"+"=gr"+id+"; expires="+date.toGMTString();$('#bien').fadeIn();$('.op').fadeOut()}else if(resp.status=='re')
{$('#repetido').fadeIn();$('.op').fadeOut()}
else{alert('Algo inesperado ocurrió en el servidor.','info')}}).fail(function(def){alert('Algo no salio bien, Sentimos mucho las molestias que esto pueda causar.')})}
else{$('#repetido').fadeIn();$('.op').fadeOut()}});$('#btn_voto3').click(function(e){e.preventDefault();var _this=$(this);if(_this.hasClass('disabled'))
return!1;var id=$('#imagen').data('encuesta');var opmultiples=$('#imagen').data('opmultiples');_this.addClass('disabled');var cookies=document.cookie;var if_cookie=!1;var lista_cookies=cookies.split(';');for(i in lista_cookies){var buscar=lista_cookies[i].search('gr'+id);if(buscar>-1){if_cookie=!0;break}};if(!if_cookie){$('.ldr').show();var checkboxValues=new Array();$('input[name="ra_opcion"]:checked').each(function(){checkboxValues.push($(this).val())});var data={ids:checkboxValues};$.post('/votar2/',data).always(function(def){$('.ldr').fadeOut();_this.removeClass('disabled')}).done(function(resp){if(resp.status=='ok')
{var date=new Date();date.setTime(date.getTime()+(90*24*60*60*1000));document.cookie="name"+"=gr"+id+"; expires="+date.toGMTString();$('#bien').fadeIn(2500);$('.op').fadeOut()}else if(resp.status=='re')
{$('#repetido').fadeIn(3300);$('.op').fadeOut()}
else{alert('Algo inesperado ocurrió en el servidor.','info')}}).fail(function(def){alert('Algo no salio bien, Sentimos mucho las molestias que esto pueda causar.')})}
else{$('#repetido').fadeIn(3300);$('.op').fadeOut()}});$(window).scroll(function(){if($(this).scrollTop()>50){$('.back-top').fadeIn()}else{$('.back-top').fadeOut()}});$('.back-top').click(function(){$('body,html').animate({scrollTop:0},800);return!1})